language: php
php:
  - 5.2
  - 5.5

before_script:
  - mysql -e 'create database newtimelist; use newtimelist;'
  - cd protected/tests/

script: phpunit unit --colors --coverage-text --exclude-group mssql,oci framework